"""Initial migration

Revision ID: 898a2cc76220
Revises: 
Create Date: 2024-12-20 18:36:38.465615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898a2cc76220'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'product_id',
               existing_type=sa.VARCHAR(),
               comment='Unique product identifier',
               existing_nullable=True)
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='Type of the product')
    op.alter_column('items', 'air_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Air temperature during operation',
               existing_nullable=True)
    op.alter_column('items', 'process_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Process temperature during operation',
               existing_nullable=True)
    op.alter_column('items', 'rotational_speed',
               existing_type=sa.INTEGER(),
               comment='Rotational speed in RPM',
               existing_nullable=True)
    op.alter_column('items', 'torque',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Torque applied in Nm',
               existing_nullable=True)
    op.alter_column('items', 'tool_wear',
               existing_type=sa.INTEGER(),
               comment='Tool wear in minutes',
               existing_nullable=True)
    op.alter_column('items', 'machine_failure',
               existing_type=sa.BOOLEAN(),
               comment='Indicates machine failure',
               existing_nullable=True)
    op.alter_column('items', 'twf',
               existing_type=sa.BOOLEAN(),
               comment='Tool wear failure',
               existing_nullable=True)
    op.alter_column('items', 'hdf',
               existing_type=sa.BOOLEAN(),
               comment='Heat dissipation failure',
               existing_nullable=True)
    op.alter_column('items', 'pwf',
               existing_type=sa.BOOLEAN(),
               comment='Power failure',
               existing_nullable=True)
    op.alter_column('items', 'osf',
               existing_type=sa.BOOLEAN(),
               comment='Overstrain failure',
               existing_nullable=True)
    op.alter_column('items', 'rnf',
               existing_type=sa.BOOLEAN(),
               comment='Random failure',
               existing_nullable=True)
    op.drop_index('ix_items_product_id', table_name='items')
    op.create_index(op.f('ix_items_product_id'), 'items', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_product_id'), table_name='items')
    op.create_index('ix_items_product_id', 'items', ['product_id'], unique=False)
    op.alter_column('items', 'rnf',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Random failure',
               existing_nullable=True)
    op.alter_column('items', 'osf',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Overstrain failure',
               existing_nullable=True)
    op.alter_column('items', 'pwf',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Power failure',
               existing_nullable=True)
    op.alter_column('items', 'hdf',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Heat dissipation failure',
               existing_nullable=True)
    op.alter_column('items', 'twf',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Tool wear failure',
               existing_nullable=True)
    op.alter_column('items', 'machine_failure',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates machine failure',
               existing_nullable=True)
    op.alter_column('items', 'tool_wear',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tool wear in minutes',
               existing_nullable=True)
    op.alter_column('items', 'torque',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Torque applied in Nm',
               existing_nullable=True)
    op.alter_column('items', 'rotational_speed',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Rotational speed in RPM',
               existing_nullable=True)
    op.alter_column('items', 'process_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Process temperature during operation',
               existing_nullable=True)
    op.alter_column('items', 'air_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Air temperature during operation',
               existing_nullable=True)
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='Type of the product')
    op.alter_column('items', 'product_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique product identifier',
               existing_nullable=True)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
